const actionType = {
    GET_PRODUCT:'GET_PRODUCT',
    GET_ONE_PRODUCT:'GET_ONE_PRODUCT',
    ADD_PRODUCT:'ADD_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELET_PRODUCT:'DELET_PRODUCT',
    SEARCH_PRODUCT:'SEARCH_PRODUCT'

}
export default actionType
